discourse_minicod_nav:
  minicodnav_plugin_enabled:
    default: true
    client: false
  minicodnav_webhook_secret:
    default: ""
    secret: true
    client: false
  minicodnav_target_category_id:
    default: 0
    client: false
  minicodnav_pavlovia_category_id:
    default: 0
    client: false
  minicodnav_journal_category_id:
    default: 0
    client: false
  minicodnav_bot_user_id:
    default: -1
    client: false
  minicodnav_archived_tag:
    default: "minicodnav-archived"
    client: false
