discourse_academic_nav:
  acadnav_plugin_enabled:
    default: true
    client: false
  acadnav_webhook_secret:
    default: ""
    secret: true
    client: false
  acadnav_target_category_id:
    default: 0
    client: false
  acadnav_pavlovia_category_id:
    default: 0
    client: false
  acadnav_shit_category_id:
    default: 0
    client: false
  acadnav_bot_user_id:
    default: -1
    client: false
  acadnav_archived_tag:
    default: "acadnav-archived"
    client: false
